<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
 A.size = 2 X 2 , B.size = 2 X 5, then resultant matrix is 2 X 5

In [40]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    
    
    # Check whether column Size of Matrix A matches with Row Size of Matrix B
    # If not , Matrix Multiplication is not possible
    if(len(A[0])!=len(B)):
        return "Matrix Multiplication not possible as Column size of A and Row Size of B do not match"
    else:
        C = list()
        # Get the column Size of Matrix B
        col_B_size = len(B[0])
        
        # Iterate over rows of Matrix A
        for row_A_values in A:
            li = list()
            # Iterate over Column indices of Matrix B
            for col_B_index in range(col_B_size):
                row_B_index = 0
                sum = 0
                #Column Size of A and Row size of B are equal, So just iterate over column values of A 
                for num_A in row_A_values:
                    
                    sum += num_A * B[row_B_index][col_B_index]
                    row_B_index+=1
                li.append(sum)    
            C.append(li)    
    return C
def get_mat_values(k):
    try:
        mat_li = list()
        print('Please enter Row Size of Matrix '+k+':')
        r = int(input())
        print('Please enter Column Size of Matrix '+k+':')
        c = int(input())
        print('Please enter the values of Matrix '+k+':')
        for i in range(r):
          li = list()
          for j in range(c):
            li.append(int(input())) 
          mat_li.append(li)  
    except Exception as ex:
        print("Exception:",ex)

    return mat_li

#Specify Matrix A and B values
A=get_mat_values('A')
B=get_mat_values('B')

m=matrix_mul(A, B)
print("Output: ")
print(m)


Please enter Row Size of Matrix A:
3
Please enter Column Size of Matrix A:
3
Please enter the values of Matrix A:
1
2
3
4
5
6
7
8
9
Please enter Row Size of Matrix B:
3
Please enter Column Size of Matrix B:
3
Please enter the values of Matrix B:
1
2
3
4
5
6
7
8
9
Output: 
[[30, 36, 42], [66, 81, 96], [102, 126, 150]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [39]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

def pick_a_number_from_list(A):
    l = sorted(A)
    s = sum(A)
    li_new = list()
    li_f = list()
    for i in l:
        li_new.append(i/s)
    tot = 0    

    for j in li_new:
        tot +=j
        li_f.append(tot)
    
    val = uniform(0,1)
    fin_val = 0
    for k in range(len(li_f)):
        if(val >= li_f[k] and val < li_f[k+1]):
            fin_val =  l[k+1]
            break
    return fin_val

def sampling_based_on_magnitued():
    finl = list()
    d = dict()
    A = [0,5,27,6,13,28,100,45,10,79]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
        finl.append(number)
    for j in finl:
        if(j in d.keys()):
            d[j]+=1
        else:
            d[j] = 1
    print(dict(sorted(d.items(), key = lambda x: x[1], reverse = True)))        
sampling_based_on_magnitued()

28
45
79
6
79
45
79
28
28
28
79
45
100
100
79
13
79
100
100
100
100
100
100
6
13
27
45
27
79
79
79
79
45
10
79
45
45
10
79
100
10
100
100
45
28
79
100
79
45
27
10
79
100
10
27
100
28
28
100
79
100
45
79
45
28
100
79
79
100
79
100
45
27
45
13
100
79
100
79
79
79
10
28
27
79
100
100
100
100
100
13
27
100
100
45
28
27
100
100
{100: 30, 79: 25, 45: 14, 28: 10, 27: 8, 10: 6, 13: 4, 6: 2}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [53]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# String: it will be the input to your program
def replace_digits(s):
    # write your code
    # 
    str_val = ''
    if(s is not None and len(s)>0):
        for p in s:
            for i in re.findall(r'[0-9]+', p):
                str_val+='#'
    else:
        return('String is not defined.')    
    return(str_val) # modified string which is after replacing the # with digits
r = input()
print(replace_digits(r))

a2b3c4
###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

import math 

def get_input(n):
    li = list()
    for i in range(int(r)):
        inp = input()
        if(n == 'names'):
            li.append('Student'+str(i+1) if len(inp) == 0 else inp)
        else:
            li.append(0 if len(inp) == 0 else inp)    
    return li    

print('Enter Total Number of students:')
r = input()

if(r is not None and len(r)>0):
    
    d = dict()
    print('Enter Student Names:')
    names = get_input('names')
    print('Enter Student Marks:')
    marks = get_input('marks')
    
    sorted_marks_desc = sorted(list(set(marks)),reverse=True)
    sorted_marks_asc = sorted(list(set(marks)))
    for i in range(len(marks)):
        if(marks[i] in d):
            l = d[marks[i]]
            l.append(names[i])
            d[marks[i]] = l
        else:    
            li = list()
            li.append(names[i])
            d[marks[i]] = li
    
    print("Top 5 Ranks:\n")
    for mark in sorted_marks_desc[0:5]:
        
        for n in d[mark]:
            print(n, mark) 

    print("Least 5 Ranks:\n")
    
    for mark in sorted_marks_asc[0:5]:
        
        for n in d[mark]:
            print(n, mark)         

    perc_index1 = round(1/4 * len(sorted_marks_asc))
    perc_index2 = math.floor(3/4 * len(sorted_marks_asc))
    print(perc_index1,perc_index2)
    for mark in sorted_marks_asc[perc_index1:perc_index2]:
        
        for n in d[mark]:
            print(n, mark)  


#top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
#print(# those values)

Enter Total Number of students:
10
Enter Student Names:
studen1
student2
student3
student4
student5
student6
student7
student8
student9
student10
Enter Student Marks:
45
78
12
14
48
43
47
98
22
80
Top 5 Ranks:

student8 98
student10 80
student2 78
student5 48
student7 47
Least 5 Ranks:

student3 12
student4 14
student9 22
student6 43
studen1 45
2 7
student9 22
student6 43
studen1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [1]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    d = dict()
    li = list()
    for item in S:
      dist = (item[0] * P[0] + item[1] * P[1])/(math.sqrt(item[0]*item[0] + item[1] * item[1] ) * math.sqrt(P[0]*P[0] + P[1] * P[1] )) 
      d[dist] = item
      li.append(dist)
    li.sort(reverse=True) 
    final_list = list()
    for dist in li[0:5]:
      final_list.append(d[dist])
    return final_list  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [2]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


def i_am_the_one(red,blue,line):
    s = [float(i) for i in re.split('[xy]', line)]
    x=s[0]
    c=s[2]
    y=s[1]
    r_up_count = 0
    r_down_count=0
    b_up_count=0
    b_down_count=0
    separator = 'NO'

    #Used the Zip function as both the lists are of equal size
    for r_p,b_p in zip(red,blue):
      
      x1 = r_p[0]
      y1 = r_p[1]
      x2 = b_p[0]
      y2 = b_p[1]
      #If Y coefficient is not zero
      if(y !=0):
        if(y1>-(x1+c)/y):
          r_up_count +=1
        elif(y1<-(x1+c)/y):
          r_down_count +=1  
        if(y2>-(x2+c)/y):
          b_up_count +=1 
        elif(y2<-(x2+c)/y):
          b_down_count +=1
      #If X coefficient is not zero and Y coefficient is zero    
      elif(x != 0):
        if(x1>-c):
          r_up_count +=1
        elif(x1<-c):
          r_down_count +=1  
        if(x2>-c):
          b_up_count +=1 
        elif(x2<-c):
          b_down_count +=1
      else:
        return("Both X and Y coefficients are zero")
    #A Line separates any two given point only when one point 
    #lies above the line and the other lies below the line  
    if((r_up_count==len(red) and b_down_count==len(blue)) or 
       (r_down_count==len(red) and b_up_count==len(blue))):
      separator= 'YES'
    return separator #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(p):
    # your code
    l = list(p.split(","))
    leng = len(l)
    d = dict()
    index = 0
    for i in l:
        try:
            if(isinstance(int(i),int)):
                
                d[index] = int(i)
                index += 1
    
        except Exception as ex:
            index += 1
            print("Exception:",ex)
    val = '' 
    li_f = list()     
    if(len(d) == 1):
        val = list(d.values())[0]/leng  
        li_f = [val for i in range(leng)]
    elif(len(d) == 2):
        li_key = list(d.keys())
        li_val = list(d.values()) 
        if(li_key[0] == 0 and li_key[1] == leng-1):
            val = (li_val[0] + li_val[1])/leng
            li_f = [val for i in range(leng)]
        else:
            s = li_val[0]/(li_key[0] + 1)
            
            p = (s + li_val[1])/(li_key[1]-li_key[0]+1)
   
            t = p/(leng-li_key[1])

            li_f = [s for i in range(li_key[0])]+ [p for i in range(li_key[1]-li_key[0])] + [t for i in range(leng-li_key[1])]
            
    return li_f

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

Exception: invalid literal for int() with base 10: '_'
Exception: invalid literal for int() with base 10: '_'
Exception: invalid literal for int() with base 10: '_'
Exception: invalid literal for int() with base 10: '_'
Exception: invalid literal for int() with base 10: '_'
Exception: invalid literal for int() with base 10: '_'
Exception: invalid literal for int() with base 10: '_'
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


def compute_conditional_probabilites(A):
    d = dict()
    d_li = dict()
    l = len(A[0])
    for i in range(len(A)):
        s = ''
        for j in range(len(A[0])):
            s += A[i][j]
            if(A[i][j] in d):
                d[A[i][j]] += 1
            else:
                d[A[i][j]] = 1
        if(s in d_li):
            d_li[s] += 1
        else:
            d_li[s] = 1    
    for i in range(5):
        for j in range(3):
            try:
                print('P(F=F'+str(i+1)+'|S==S'+str(j+1) +')' + '=' + str(d_li['F'+str(i+1)+'S'+str(j+1)]/d['S'+str(j+1)]))
            except:
                print('P(F=F'+str(i+1)+'|S==S'+str(j+1) + '=' + str(0))
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)=0.25
P(F=F1|S==S2)=0.3333333333333333
P(F=F1|S==S3=0
P(F=F2|S==S1)=0.25
P(F=F2|S==S2)=0.3333333333333333
P(F=F2|S==S3)=0.3333333333333333
P(F=F3|S==S1=0
P(F=F3|S==S2)=0.3333333333333333
P(F=F3|S==S3)=0.3333333333333333
P(F=F4|S==S1)=0.25
P(F=F4|S==S2=0
P(F=F4|S==S3)=0.3333333333333333
P(F=F5|S==S1)=0.25
P(F=F5|S==S2=0
P(F=F5|S==S3=0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    set_1 = set(S1.split(' '))
    set_2 = set(S2.split(' '))
    a = list(set_1.intersection(set_2))
    b=list(set_1.symmetric_difference(a))
    c=list(set_2.symmetric_difference(a))
    
    return a,b,c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)

print('Number of common words between S1, S2:' , a)
print('Words in S1 but not in S2: ' , b)
print('Words in S2 but not in S1: ' , c)

Number of common words between S1, S2: ['contain', 'the', 'column', 'uniques', 'will', 'only', 'values']
Words in S1 but not in S2:  ['first', 'F', '5']
Words in S2 but not in S1:  ['S', '3', 'second']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    n = len(A)
    loss = 0
    for i in range(n):
      loss +=   ((A[i][0] * math.log10(A[i][1])) + (1-A[i][0] * math.log10(1-A[i][1])))
    final_loss = -1/n * loss  
    return final_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

-1.0532460915340351
